{
 "title": "Aqua Monitor - 3.0.3 - HomeAway",
 "description": "Docker monitoring with prometheus and cAdvisor",
 "tags": [ "docker" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "imagename",
    "query": "container_last_seen{job=\"cadvisor\",image=~\"aqua.*\"}"
   },
   {
    "name": "node",
    "query": "container_last_seen{job=\"cadvisor\"}"
   },
   {
    "name": "testname",
    "query": "select testname from aqua_monitor order by timestamp desc;"
   }
  ]
 },
 "panels": [
  {
   "title": "Connected Agents",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp),\n  agents_connected\nFROM\n  aqua_monitor\nWHERE\n  $__timeFilter(timestamp) and testname=$testname\n"
    }
   ]
  },
  {
   "title": "Disconnected Agents",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "SELECT\r\n  $__time(timestamp),\r\n  agents_disconnected\r\nFROM\r\n  aqua_monitor\r\nWHERE\r\n  $__timeFilter(timestamp) and testname=$testname",
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  agents_disconnected\r\nFROM\r\n  aqua_monitor\r\nWHERE\r\n  $__timeFilter(timestamp) and testname=$testname"
    }
   ]
  },
  {
   "title": "Online Scanners",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  scanners_online\r\nFROM\r\n  aqua_monitor\r\nWHERE\r\n  $__timeFilter(timestamp) and testname=$testname"
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_last_seen{instance=~'$node',image=~'$imagename'})"
    }
   ]
  },
  {
   "title": "Aqua Statistics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  scanq_pending,scanq_progress,scanq_finished,scanq_failed,scanners_online,scanq_spm,scanq_spmps\r\n  from\r\n  aqua_monitor\r\nWHERE\r\n  $__timeFilter(timestamp) and testname=$testname"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{instance=~'$node',image=~'$imagename'}[5m]) * 100 / 4) by (image, instance)",
     "legendFormat": "{{image}} - {{instance}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=~'$node',image=~'$imagename'}) by (image,instance)",
     "legendFormat": "{{image}}  --  {{instance}}"
    }
   ]
  },
  {
   "title": "Network - Received Bytes - Containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{instance=~'$node',image=~'$imagename'}[5m])) by (image,instance)",
     "legendFormat": "{{image}}  - {{instance}}"
    }
   ]
  },
  {
   "title": "Network - Transmit Bytes - Containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{instance=~'$node',image=~'$imagename'}[5m])) by (image,instance)",
     "legendFormat": "{{image}} - {{instance}}"
    }
   ]
  },
  {
   "title": "File System - Usage - Containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{instance=~'$node',image=~'$imagename'}) by (image,instance)",
     "legendFormat": "{{image}} - {{instance}}"
    }
   ]
  }
 ]
}