global:
  scrape_interval:     10s
  evaluation_interval: 10s

  # Attach these labels to any time series or alerts when communicating with 
  # external systems (federation, remote storage, Alertmanager).
scrape_configs:
  - job_name: 'dummy'
    scrape_interval: 10s
    file_sd_configs:
      - files:
        - targets.json
